name: CI

on: [push]

jobs:
  pushcommit:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: commit something and push
      run: |
        ls -la > text
        git add text
        git commit -m 'test add'
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
